-- USUARIOS INICIALES
INSERT INTO USERS (ID, LOGIN, NAME, SURNAME1, PASSWORD) VALUES (DEFAULT, 'demo', 'Demo', 'Demo', 'C5rCRzh9s2DPHYrnnLS/eg==');

-- PERFILES INICIALES
INSERT INTO PROFILES (ID, NAME, DESCRIPTION) VALUES (DEFAULT, 'Administrador', 'Acceso general');

-- SECCIONES INICIALES
INSERT INTO SECTIONS (ID, NAME, DESCRIPTION, ALIAS) VALUES(DEFAULT, 'Contactos', 'Perfiles y secciones a los que puede acceder cada perfil.', 'CONTACTS');

-- RELACIONES PERFILES-SECCIONES INICIALES
INSERT INTO PROFILES_SECTIONS_MAP (PROFILE_ID, SECTION_ID) VALUES (1,1);

-- RELACIONES USUARIOS-PERFILES INICIALES
INSERT INTO USERS_PROFILES_MAP (USER_ID, PROFILE_ID) VALUES (1,1);