server:
  port: 9999
  
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://45.84.210.174:65432/Fullstack_2022_2_G4
    username: Fullstack_2022_2_G4
    password: y1JOQ3T9igItgfgE
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
  # subida de imagenes  
  servelet:
        multipart:
          max-file-size: 10MB
          max-request-size: 10MB

# oauth2 configuration  
security:
  oauth2:
    client:
      client-id: demo
      client-secret: 8Fjkk59bXKws8bmMNFZB
      authorized-grant-types: password,authorization_code,refresh_code,implicit
      scope: openid
      
demo:
  oauth:
    enabled: true
    accessTokenValiditySeconds: 86400
    refreshTokenValiditySeconds: 86400